# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-16 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('salary', models.FloatField()),
                ('bonus', models.FloatField()),
            ],
        ),
    ]
